@props(['prefix' => 'scoring', 'initial' => []])

@php
    // Existing props:
    // $prefix (e.g., 'scoring'), $initial (may contain resources/collections)

    // 1) Variables
    $initialVarsRaw = old($prefix . '.variables', $initial['variables'] ?? []);

    if ($initialVarsRaw instanceof \Illuminate\Http\Resources\Json\ResourceCollection) {
        // resource collection → safe array without needing request()
        $initialVarsRaw = $initialVarsRaw->jsonSerialize();
    } elseif ($initialVarsRaw instanceof \Illuminate\Support\Collection) {
        // laravel collection
        $initialVarsRaw = $initialVarsRaw->values()->toArray();
    } elseif (is_object($initialVarsRaw) && method_exists($initialVarsRaw, 'toArray')) {
        // plain resource or arrayable object
        // prefer toArray(request()) if available, fall back to ->toArray()
        try {
            $initialVarsRaw = $initialVarsRaw->toArray(request());
        } catch (\Throwable $e) {
            $initialVarsRaw = $initialVarsRaw->toArray();
        }
    }

    // ensure plain, indexed array
    $initialVars = array_values((array) $initialVarsRaw);

    // 2) Condition / formula
    $initialCondition = old(
        $prefix . '.condition',
        old($prefix . '.formula', $initial['condition'] ?? ($initial['formula'] ?? '')),
    );

    // Check if we have existing formula data with ID (for updates)
    $hasExistingFormula = !empty($initial['condition']) && !empty($initial['formula_id'] ?? null);
    $formulaId = $initial['formula_id'] ?? null;
@endphp


<div x-data="{
    prefix: '{{ $prefix }}',
    vars: (@js($initialVars)).map(v => {
        const variable = {
            id: Date.now() + Math.random(),
            dbId: v.id ?? null, // Store database ID
            variable_name: v.variable_name ?? v.name ?? '',
            label_name: v.label_name ?? v.variable_name ?? v.name ?? '',
            type: (v.type ?? 'defined'),
            value: ((v.type ?? 'defined') === 'defined') ? (v.value ?? '') : ''
        };

        // If variable_name doesn't follow the pattern, regenerate it
        const typePattern = new RegExp(`^${variable.type}_\\d+$`);
        if (!typePattern.test(variable.variable_name)) {
            // Will be regenerated by initializeVariableNames
            variable.needsRename = true;
        }

        return variable;
    }),
    condition: @js($initialCondition),

    // inputs for adding a new var
    newName: '',
    newLabel: '',
    newType: 'defined',
    newValue: '',

    // Computed property to check if there's already an output variable
    get hasOutputVariable() {
        return this.vars.some(v => v.type === 'output');
    },

    // Helper function to generate variable name based on type
    generateVariableName(type) {
        const typePrefix = type || 'defined';
        const sameTypeVars = this.vars.filter(v => v.type === typePrefix);
        const nextNumber = sameTypeVars.length + 1;
        return `${typePrefix}_${nextNumber}`;
    },

    add() {
        const label = (this.newLabel || '').trim();
        if (!label) {
            this.showToast('กรุณากรอกป้ายชื่อ (label_name)', 'error');
            return;
        }

        // Check if trying to add output when one already exists
        if (this.newType === 'output' && this.hasOutputVariable) {
            this.showToast('สามารถมีตัวแปรประเภท Output ได้เพียง 1 ตัวเท่านั้น', 'error');
            return;
        }

        const generatedName = this.generateVariableName(this.newType);

        this.vars = [
            ...this.vars,
            {
                id: Date.now() + Math.random(),
                dbId: null, // New variables don't have database ID
                variable_name: generatedName,
                label_name: label,
                type: this.newType,
                value: this.newType === 'defined' ? (this.newValue ?? '') : ''
            }
        ];
        this.newName = '';
        this.newLabel = '';
        this.newType = 'defined';
        this.newValue = '';
        this.$nextTick(() => this.$refs.newLabel?.focus());
    },

    remove(i) {
        const a = [...this.vars];
        a.splice(i, 1);
        this.vars = a;

        // Regenerate variable names to maintain proper numbering
        this.regenerateVariableNames();
    },

    // Helper function to regenerate all variable names when variables are removed
    regenerateVariableNames() {
        const typeCounters = {};

        this.vars.forEach(v => {
            const type = v.type || 'defined';
            typeCounters[type] = (typeCounters[type] || 0) + 1;
            v.variable_name = `${type}_${typeCounters[type]}`;
        });
    },

    // Initialize variable names for existing variables that don't follow the pattern
    initializeVariableNames() {
        let hasChanged = false;
        this.vars.forEach(v => {
            if (v.needsRename) {
                hasChanged = true;
                delete v.needsRename;
            }
        });

        if (hasChanged) {
            this.regenerateVariableNames();
        }
    },

    insert(text) {
        const el = this.$refs.condition;
        const s = el.selectionStart ?? el.value.length;
        const e = el.selectionEnd ?? el.value.length;
        const before = el.value.slice(0, s),
            after = el.value.slice(e);
        this.condition = before + text + after;
        this.$nextTick(() => {
            el.focus();
            const pos = s + text.length;
            el.setSelectionRange(pos, pos);
        });
    },

    // --- validation helpers (unchanged) ---
    reserved() { return new Set(['IF', 'AND', 'OR', 'NOR', 'XOR', 'XNOR', 'NAND', 'NOT', 'TRUE', 'FALSE', 'ELSE', 'THEN']); },
    extractVars(text) {
        const tokens = (text || '').match(/[A-Za-z_][A-Za-z0-9_]*/g) || [];
        const set = new Set(),
            r = this.reserved();
        tokens.forEach(t => { if (!r.has(t) && isNaN(Number(t))) set.add(t); });
        return Array.from(set);
    },
    get declaredVars() { return this.vars.map(v => (v.variable_name || '').trim()).filter(Boolean); },
    get referencedVars() { return this.extractVars(this.condition); },
    get unknownVars() {
        const d = new Set(this.declaredVars);
        return this.referencedVars.filter(n => !d.has(n));
    },
    initSubmitGuard() {
        const form = this.$el.closest('form');
        if (!form) return;
        form.addEventListener('submit', (e) => {
            if (this.unknownVars.length) {
                e.preventDefault();
                alert('พบตัวแปรที่ยังไม่ได้ประกาศ: ' + this.unknownVars.join(', '));
            }
        });
    }
}" x-init="initSubmitGuard();
initializeVariableNames();" class="space-y-5">

    <div class="grid grid-cols-1 md:grid-cols-[1fr,200px,auto] gap-3 items-center">
        <label class="block text-slate-800 font-medium">สร้างตัวแปร</label>

        <input x-ref="newLabel" x-model="newLabel" type="text" placeholder="ป้ายชื่อ (เช่น statA, input1)"
            class="p-2 w-full bg-white rounded-xl border border-slate-300 placeholder-slate-400 text-sm md:text-base hover:border-blue-400 transition" />

        <div class="flex gap-3 items-center">
            <select x-model="newType"
                class="p-2 w-full bg-white rounded-xl border border-slate-300 placeholder-slate-400 text-sm md:text-base hover:border-blue-400 transition">
                <option value="defined">Defined</option>
                <option value="output" x-show="!hasOutputVariable || newType === 'output'">Output</option>
                <option value="input">Input</option>
            </select>

            <template x-if="newType === 'defined'">
                <input x-model="newValue" type="number" placeholder="ค่า"
                    class="p-2 w-full bg-white rounded-xl border border-slate-300 placeholder-slate-400 text-sm md:text-base hover:border-blue-400 transition">
            </template>
        </div>

        <button type="button" @click="add()"
            class="justify-self-start md:justify-self-end inline-flex items-center gap-2 rounded-xl border border-blue-500 text-blue-600 px-3 py-2 md:px-4 md:py-2 hover:bg-blue-50 text-sm md:text-base">
            เพิ่มตัวแปร <span class="text-xl leading-none">＋</span>
        </button>
    </div>

    <template x-for="(v, i) in vars" :key="v.id">
        <div
            class="flex flex-col md:flex-row md:items-center gap-2 md:gap-3 bg-white rounded-2xl border border-slate-200 px-4 py-3">
            <div class="flex flex-col gap-1 flex-1">
                <div class="text-xs text-slate-500">Variable Name (Auto-generated)</div>
                <div class="text-blue-700 font-medium text-sm md:text-base" x-text="v.variable_name"></div>
            </div>

            <div class="flex flex-col gap-1 flex-1">
                <div class="text-xs text-slate-500">Label Name</div>
                <input x-model="v.label_name"
                    class="bg-transparent border-0 focus:ring-0 text-slate-700 font-medium text-sm md:text-base p-0"
                    placeholder="label_name" />
            </div>

            <span class="md:w-24 text-sm text-slate-600 md:text-left"
                x-text="v.type === 'defined' ? 'Static' : (v.type === 'input' ? 'Input' : 'Output')"></span>

            <template x-if="v.type === 'defined'">
                <input x-model.number="v.value" type="number"
                    class="w-24 rounded-xl border-slate-300 focus:border-blue-500 focus:ring-blue-500 text-sm md:text-base" />
            </template>
            <template x-if="v.type === 'input'">
                <span class="text-slate-500 text-sm">ค่าที่ผู้ใช้ต้องกรอก</span>
            </template>
            <template x-if="v.type === 'output'">
                <span class="text-slate-500 text-sm">ค่าผลลัพธ์จากสูตร</span>
            </template>

            <button type="button" @click="remove(i)"
                class="md:ml-2 text-slate-500 hover:text-red-600 text-sm md:text-base">✕</button>

            {{-- Hidden fields for POST --}}
            <input type="hidden" :name="`${prefix}[variables][${i}][variable_name]`" :value="v.variable_name">
            <input type="hidden" :name="`${prefix}[variables][${i}][label_name]`" :value="v.label_name">
            <input type="hidden" :name="`${prefix}[variables][${i}][type]`" :value="v.type">
            <input type="hidden" :name="`${prefix}[variables][${i}][value]`" :value="v.value ?? ''">
            {{-- Hidden field for existing variable ID --}}
            <template x-if="v.dbId">
                <input type="hidden" :name="`${prefix}[variables][${i}][id]`" :value="v.dbId">
            </template>
        </div>
    </template>

    <div class="space-y-3">
        <label class="block text-slate-800 font-medium">สร้างเงื่อนไขการคำนวณ</label>
        <textarea x-ref="condition" x-model="condition" rows="5"
            class="w-full bg-white rounded-2xl border border-blue-200 focus:border-blue-500 focus:ring-blue-500 p-3 text-sm md:text-base"
            placeholder="ตัวอย่าง: defined_1 * input_1"></textarea>

        <template x-if="unknownVars.length">
            <div class="rounded-xl border border-red-200 bg-red-50 text-red-700 p-3 text-sm">
                พบตัวแปรที่ยังไม่ได้ประกาศ: <span x-text="unknownVars.join(', ')"></span>
            </div>
        </template>
        <template x-if="!unknownVars.length && condition && condition.trim().length">
            <div class="rounded-xl border border-emerald-200 bg-emerald-50 text-emerald-700 p-3 text-sm">
                ✓ ตัวแปรทั้งหมดที่ใช้งานในเงื่อนไขถูกประกาศแล้ว
            </div>
        </template>

        <div class="space-y-2">
            <div class="text-slate-700 font-medium">เครื่องหมาย</div>
            <div class="flex flex-wrap gap-2">
                <template x-for="op in ['+','-','*','/','<','>','<=','>=','==','!=','IF(']">
                    <button type="button" @click="insert(op)"
                        class="px-3 py-1 rounded-xl bg-white text-slate-800 hover:bg-blue-100 text-sm">
                        <span x-text="op"></span>
                    </button>
                </template>
            </div>

            <div class="text-slate-700 font-medium mt-2">คำสั่ง</div>
            <div class="flex flex-wrap gap-2">
                <template x-for="op in ['AND','OR','NOR','XOR','XNOR','NAND','NOT']">
                    <button type="button" @click="insert(op)"
                        class="px-3 py-1 rounded-xl bg-white text-slate-800 hover:bg-blue-100 text-sm">
                        <span x-text="op"></span>
                    </button>
                </template>
            </div>

            <div class="text-slate-700 font-medium mt-2">ตัวแปร</div>
            <div class="flex flex-wrap gap-2">
                <template x-for="(v, i) in vars" :key="'chip' + v.id">
                    <button type="button" @click="insert(v.variable_name)"
                        class="px-3 py-1 rounded-full bg-slate-300 hover:bg-slate-200 text-slate-800 text-sm">
                        <span x-text="v.variable_name || 'var' + (i+1)"></span>
                    </button>
                </template>
            </div>
        </div>

        {{-- Hidden field for POST --}}
        <input type="hidden" :name="`${prefix}[condition]`" :value="condition">

        @if ($formulaId)
            {{-- Hidden field for existing formula ID --}}
            <input type="hidden" name="{{ $prefix }}[formula_id]" value="{{ $formulaId }}">
        @endif
    </div>
</div>
